name: Generate APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build WebView APK
        uses: jaywcjlove/github-action-android-apk@main
        with:
          apk-name: 'MediaTracker.apk'
          package-name: 'com.yamini.mediatracker'
          scheme: 'https'
          url: 'https://example.com'

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: '*.apk'
